import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

const supabase = createClient(supabaseUrl, supabaseKey);

async function clean() {
  console.log("Initiating complete global Sandbox cache purge...");

  // Delete all shadow cache. The immutable WhatsApp `messages` table is untouched.
  const { data: d1, error: e1 } = await supabase
    .from('ai_training_messages')
    .delete()
    .neq('id', '00000000-0000-0000-0000-000000000000'); // hack to delete all rows easily in Supabase REST
    
  console.log("Wiped ai_training_messages cache. Errors:", e1 ? e1.message : 'None');

  // Delete all decisions generated by the background daemon
  const { data: d2, error: e2 } = await supabase
    .from('ai_reply_decisions')
    .delete()
    .eq('sent_by', 'ai_worker_sync');
    
  console.log("Wiped daemon-generated ai_reply_decisions. Errors:", e2 ? e2.message : 'None');
}

clean();
